### ISSUE TITLE
RecipeEditor adds extra suppression slots when using the enum mask field.

### ISSUE THREAD

**Issue by cwmanley** [umasteeringgroup/UMA#176] opened 2018-11-12 01:48 UTC
Suppression mask field adds extra suppression slots when there is a high number of wardrobe slots.

**Comment by kenamis** [comment] 2019-01-28 19:20
can you expand on this and/or describe a way to reproduce the error?

**Comment by Jaimi** [comment] 2020-05-28 18:43
This is fixed in 2.10 update 1. The problem was rollover due to the flags control used.

**Closed by Jaimi** 2020-05-28 18:43 UTC
Labels: bug
