### ISSUE TITLE
Errors in scene when UMA installed but not used

### ISSUE THREAD

**Issue by jwvanderbeck** [umasteeringgroup/UMA#240] opened 2019-02-24 00:34 UTC
**Describe the bug**
With UMA installed in the project but not used in a scene, UMA will throw errors in play mode.  Additionally it will add an undesired scene object

**Environment (please complete the following information):**
 - Unity Version: Unity 2018.3.4f1
 - UMA Version: 2.8.0
 - Platform Build (if not editor): Editor

**To Reproduce**
1. Add UMA to the project
2. Create a new empty scene
3. In the hierarchy there will be a new object named "UMAEditorContext" that can not be deleted
4. Press Play in Editor
5. UMA throws exception errors

**Expected behavior**
If UMA is not being used in a scene, I expect not UMA errors to be thrown and no UMA objects to be added to the scene

**Additional context**
NullReferenceException: Object reference not set to an instance of an object
UMA.Editors.RecipeEditor.OnEnable () (at Assets/UMA/Core/Extensions/DynamicCharacterSystem/Scripts/Editor/RecipeEditor.cs:98)

**Comment by Jaimi** [comment] 2019-03-17 03:49
This is by design if you have a recipe selected.  If you have a recipe selected, and the open scene does not have a UMAContext, then it needs to create one to be able to show the editor. Before we did this, it would simply error out with an access violation. We tried an iteration where we notified the user that a scene with a "valid umacontext must be open to be able to the see recipe", but that fell flat also. In the end, we compromised on just making a context, and then cleaning it up when the editor was closed.

So in your case, you must have a recipe selected (the recipe editor is what is throwing the error). 
We will be rewriting the whole library/context/etc stuff in version 3.0 so this will no longer be a problem.  Closing this issue due to a trello task already existing to address it.

**Closed** 2019-03-17 03:49 UTC
Labels: bug
