### ISSUE TITLE
AssetIndexer Error: 2018.3.0f + UMA 2.8RC3 Win10

### ISSUE THREAD

**Issue by dza6549** [umasteeringgroup/UMA#209] opened 2019-02-03 00:51 UTC
Hi there

Not sure if this is "serious" - the DCS Demo scene appears to work. Just starting with UMA so not really sure about anything yet :)

Let me know if I can provide more info. Cheers!

Unity 2018.3.0f2
Win 10
UMA 2.8 RC3

Unable to load the AssetIndexer. This item is used to index non-asset bundle resources and is required.
UnityEngine.Debug:LogError(Object)
UMA.UMAAssetIndexer:get_Instance() (at Assets/UMA/Core/Extensions/DynamicCharacterSystem/Scripts/UMAAssetIndexer.cs:109)
UMA.UMAEditorUtilities:.cctor() (at Assets/UMA/Core/Scripts/Editor/UMAEditorUtilities.cs:40)
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes()

**Comment by dza6549** [comment] 2019-02-03 01:31
lol @kenamis  I'm a coder - so I always say "appears" - without any real testing and especially if I am just starting out - I may have missed a button. 

I've just gone through the examples and they all work fine. (Female expressions don't work - I'll let you know when I play some more)

No this is a clean install of RC3 on an empty 2018.3 project.

Do let me know if I can help out tracking this down. Cheers

**Comment by jwvanderbeck** [comment] 2019-02-05 02:36
Getting the same errors.  Unity 2018.3.4f1, UMA 2.8 RCS from Github, clean install into new Unity project. Downloaded the .unitypackage and imported.

Only other assets in the project are Cinemachine and the new NavMesh Components

```
Unable to load the AssetIndexer. This item is used to index non-asset bundle resources and is required.
UnityEngine.Debug:LogError(Object)
UMA.UMAAssetIndexer:get_Instance() (at Assets/UMA/Core/Extensions/DynamicCharacterSystem/Scripts/UMAAssetIndexer.cs:109)
UMA.CharacterSystem.UMAAssetPostProcessor:OnPostprocessAllAssets(String[], String[], String[], String[]) (at Assets/UMA/Core/Extensions/DynamicCharacterSystem/Scripts/UMAAssetModificationProcessor.cs:14)
UnityEditor.AssetPostprocessingInternal:PostprocessAllAssets(String[], String[], String[], String[], String[])
```

**Comment by kenamis** [comment] 2019-02-05 02:40
Sometimes I can get the error to appear too when upgraded from a previous version of Unity, but it doesn't prevent compile and everything still works.  The error goes away after the first run.  @jwvanderbeck are you not able to run the scenes at all?

I think the issue is with Unity not loading the Resources in time which is odd.

**Comment by kenamis** [comment] 2019-02-05 04:01
@Jaimi 
http://www.createdbyx.com/post/2013/02/17/Unity-Tip-101-55-%E2%80%93-InitializeOnLoad-ResourcesLoad-gotcha%E2%80%99s.aspx

**Comment by Jaimi** [comment] 2019-02-10 05:16
AssetDatabase is not available outside of the editor.  I will put in a change to delay load the AssetIndex in the editor utilities, and then remove the warning when it is null. We only put it in because one person deleted the file, causing it not to be found. Being not found in the post processor is not a problem, so it shouldn't warn anyway.  Fixed in Release-28-prep

**Closed by Jaimi** 2019-02-10 05:16 UTC
