### ISSUE TITLE
 version on 2.13 alpha 2  on Android Platform  have a bad rendering.

### ISSUE THREAD

**Issue by FzuLiWei** [umasteeringgroup/UMA#391] opened 2022-08-02 03:26 UTC
**Describe the bug**
 I used  github version on 2.13 alpha 2  . When I pack it on Android Platform , it come some black pixel on Characters in Unity 2019.4.29f .

**Environment (please complete the following information):**
 - Unity Version: 2019.4.29f
 - UMA Version: 2.13 alpha2
 - Rendering Pipeline: standard
 - Platform Build (if not editor): android

![image](https://user-images.githubusercontent.com/7477767/182285214-72e78608-8d96-4348-a575-95e5076cf010.png)

can you invite me on Discord . I search for UMA but not us . can not find us.

**Comment by Jaimi** [comment] 2022-08-02 16:29
This i usually caused by the slot on the outfit not matching the base slot. For example, if you put the regular underwear onto the high def body, this will happen. It's because the underwear slot has the body slot in it, with the underwear on top. When adding to the regular body, this becomes a duplicate, and is merged out (the overlay is added to the real one).  If there is a slot mismatch, then both are added. 

Here is the invite to discord:  https://discord.gg/PJEZ4REtfH

**Comment by FzuLiWei** [comment] 2022-08-03 03:09
Thank you for  invite me.  This is the Scene "UMA DCS Demo" , I do  not modify any thing, but  I have find this error . Look at pic, I modified the Texture without mipmap , it render normally.

![2022 08 03_李炜 d5d8e787fe41b34e69c68e63694172be](https://user-images.githubusercontent.com/7477767/182514516-e5c9e512-6f14-4606-abfc-bff740122a8e.png)

**Comment by Jaimi** [comment] 2024-03-26 13:53
Mobile devices should not turn on "Convert Rendertexture" due to shared memory. Changed default on mobile, but have to manually change for scenes that are converted to mobile.

**Closed by Jaimi** 2024-03-26 13:53 UTC
Labels: bug
