### ISSUE TITLE
A strange error

### ISSUE THREAD

**Issue by tomaszzackiewicz** [umasteeringgroup/UMA#52] opened 2017-10-13 18:07 UTC
Hi,

Unity 2017.2:

SkinnedMeshRenderer: Trying to set a mesh ("") that is unfit for use with SkinnedMeshRenderer. Most likely it doesn't have Skin information and/or is only assigned to the renderer during runtime, in which case Unity isn't aware of its use with SkinnedMeshRenderer. Mark the mesh as Readable or assign it to the renderer in the Editor before building.
UnityEngine.SkinnedMeshRenderer:set_sharedMesh(Mesh)
MF3D.UMADefaultMeshCombiner:MakeRenderer(Int32, Transform) (at Assets/UMA/Core/StandardAssets/UMA/Scripts/UMADefaultMeshCombiner.cs:96)
MF3D.UMADefaultMeshCombiner:EnsureUMADataSetup(UMAData) (at Assets/UMA/Core/StandardAssets/UMA/Scripts/UMADefaultMeshCombiner.cs:44)
MF3D.UMADefaultMeshCombiner:UpdateUMAMesh(Boolean, UMAData, Int32) (at Assets/UMA/Core/StandardAssets/UMA/Scripts/UMADefaultMeshCombiner.cs:117)
MF3D.UMAGeneratorBuiltin:UpdateUMAMesh(Boolean) (at Assets/UMA/Core/StandardAssets/UMA/Scripts/UMAGeneratorBuiltin.cs:282)
MF3D.UMAGeneratorBuiltin:HandleDirtyUpdate(UMAData) (at Assets/UMA/Core/StandardAssets/UMA/Scripts/UMAGeneratorBuiltin.cs:226)
MF3D.UMAGeneratorBuiltin:OnDirtyUpdate() (at Assets/UMA/Core/StandardAssets/UMA/Scripts/UMAGeneratorBuiltin.cs:265)
MF3D.UMAGeneratorBuiltin:Work() (at Assets/UMA/Core/StandardAssets/UMA/Scripts/UMAGeneratorBuiltin.cs:132)
MF3D.UMAGeneratorBuiltin:Update() (at Assets/UMA/Core/StandardAssets/UMA/Scripts/UMAGeneratorBuiltin.cs:97)

**Comment by ecurtz** [comment] 2017-10-13 18:10
This is a Unity bug, and a duplicate of issue #42 . If it's back in a released version of Unity you'll have to get the issue number from there and report it to them.

**Closed by ecurtz** 2017-10-13 18:10 UTC

**Comment by tomaszzackiewicz** [comment] 2017-10-13 18:11
OK, thank you.
